{% set name = "splot" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6edcaee24cd417965c378c5bc87414d02806915950c138c1f6e40f1a1de5286b

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

    - esda
    - geopandas >=0.9.0
    - giddy
    - libpysal
    - mapclassify
    - matplotlib >=3.3.3
    - numpy
    - packaging
    - seaborn >=0.11.0
    - spreg
    # ipywidgets required in readme
    - ipywidgets

{% set tests_to_skip = "" %}
# skip test_moran_scatterplot, because Guerry.shp is not a built in libpysal example
{% set tests_to_skip = tests_to_skip + "test_moran_ or test_plot_moran" %}
# skip tests for py39 because libpysal is available on an older version
# and tests fail with TypeError: 'MultiPolygon' object is not iterable 
{% set tests_to_skip = tests_to_skip + " or test_dynamic_lisa" %}  # [py<310]
{% set tests_to_skip = tests_to_skip + " or test_plot_local_autocorrelation" %}  # [py<310]
{% set tests_to_skip = tests_to_skip + " or test_plot_spatial_weights" %}  # [py<310]

test:
  imports:
    - splot
    - splot.esda
    - splot.giddy
    - splot.libpysal
    - splot.mapping
  requires:
    - pip
    - pytest
    - nose
    # bokeh: AttributeError: unexpected attribute 'plot_width'
    - bokeh <3.0.0a0  # [py<312]
    - bokeh           # [py>=312]
  commands:
    - pip check
    # check that pip gets the correct version 
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv --pyargs splot -k "not ({{ tests_to_skip }})"

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Lightweight plotting and mapping to facilitate spatial analysis with PySAL
  description: |
    splot connects spatial analysis done in PySAL to different popular visualization
    toolkits like matplotlib. The splot package allows you to create both static plots
    ready for publication and interactive visualizations for quick iteration and
    spatial data exploration. The primary goal of splot is to enable you to visualize
    popular PySAL objects and gives you different views on your spatial analysis workflow.
  doc_url: https://splot.readthedocs.io
  dev_url: https://github.com/pysal/splot

extra:
  recipe-maintainers:
    - slumnitz
    - knaaptime
