travis:
  secure:
    BINSTAR_TOKEN: Hc8LnG3iuHr7RZZIXXl4gfzmBqKwaXCvoXNiM6jQjw8rd5q+7NjNaAHThyNFAQ1An0YiHfVoRP3bsNCsUoUR2KZm7pLAgI3mMrODoYs+CcsjpYK19Am9oupWqX9ZPrKAyQTPDpmxJP/nKBqHaK0zaTL2vhcJZrhJEHMDgBNmNFXb08Qc6P6VseE7LuPuCelDIc6KM5tI2sdq83nqAQGXrK5p3vjh3spb6SNyhyO07NaPvXftwNZjuLMaZVXXa2twfaf4ifrjZGrK8OaOYLtY+nuew+v64gqKiRe7JsCKSuCUVD7RBCmpP+kkU1iVjWtOAOP8ivUphtHPAxMb8+2tJVGKSv7fpp1eUBUA8wyCwnilWUetDVWEn3iz+YoaDzoxVBR8S56cWqlYw7B3DAaMcbPDWbbSuMXxZDuEPP4lIknOu2qCltNAb2QwpQcAub0gUtylmnb4D2GDM3vPcwnBHshpuDrXQ9A/doxYaO3DnzGLPA57U9dpLCo+TUP9BRJSGIgnViQUzkdCvGX/aoXINHkwdKjryKTDfvBz0sj0Su3TrTG2CHwtNLytxM/2Lfk/M1fU0z4rheKPe+fGppe5VfK+vlJCbod3ed3K/KoSwXUJDfdvhixhvRu2fjTZ8hzfuz3u0MFgFkbhfxNxAYJuY/usHTcAZSlN5kHtRhqpV0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
